// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Panel struct {
	Idpanel    int32
	Identifier string
	Dscpanel   string
	NumSerie   string
	Active     sql.NullInt32
	CtrlBright sql.NullInt32
	DthrIns    sql.NullTime
	DthrAlt    sql.NullTime
}

type Sinc3 struct {
	Idsinc   int32
	Idpanel  string
	Tag      string
	Data     sql.NullString
	DthrIns  sql.NullTime
	Sinc     int32
	DthrSinc sql.NullTime
}
